export enum InvoiceStatusEnum {
    ACTIVE = 'ACTIVE',
    CANCELLED = 'CANCELLED',
    EXPIRED = 'EXPIRED',
    PENDING = 'PENDING',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    PENDING_RENEWAL = 'PENDING_RENEWAL',
    TRIAL = 'TRIAL',
    FREE = 'FREE',
    FREE_TRIAL = 'FREE_TRIAL',
    FREE_TRIAL_EXPIRED = 'FREE_TRIAL_EXPIRED',
}
