export enum EWaServerStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  RECONNECTING = 'RECONNECTING',
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  DELETED = 'DELETED',
}
