export enum PaymentTypeEnum {
    CreditCard = 'CREDIT_CARD',
    DebitCard = 'DEBIT_CARD',
    Cash = 'CASH',
    Pix = 'PIX',
    MobilePayment = 'MOBILE_PAYMENT',
    Check = 'CHECK',
    Cryptocurrency = 'CRYPTOCURRENCY',
    ElectronicBanking = 'ELECTRONIC_BANKING',
    MoneyOrder = 'MONEY_ORDER',
    PrepaidCard = 'PREPAID_CARD',
    EWallet = 'E_WALLET',
    DirectDebit = 'DIRECT_DEBIT',
    Paypal = 'PAYPAL',
    CheckoutPro = 'CHECKOUTPRO',
    WireTransfer = 'WIRE_TRANSFER',
    GiftCard = 'GIFT_CARD',
    Voucher = 'VOUCHER',
    Billing = 'BILLING',
}